baseurl = "http://www.janalonzo.com"
languageCode = "en-us"
title = "Jan Michael Alonzo"
desription = "My personal blog, notes, and some photography here and there"
canonifyurls = true

[indexes]
    category = "categories"
    tag = "tags"

[params]
    Description = "When I'm not juggling code, I go out and photograph some of the amazing places and beaches in Sydney. Dreamer. Builder. Learner."
    twitter = "jmalonzo"
    github = "jmalonzo"
    gplus = "+JanMichaelAlonzo"
    linkedin = "jmalonzo"
    facebook = "jmalonzo"
