baseurl = "https://www.janalonzo.com/"
languagecode = "en-US"
canonifyurls = true
title = "/public"
author = "Jan"
pygmentsstyle       = "bw"
pygmentscodefences  = true

[indexes]
    category = "categories"
    tag = "tags"

[params]
  sitename = "/public"

[[menu.main]]
    name = "Twitter"
    url  = "https://twitter.com/jmalonzo"
[[menu.main]]
    name = "Github"
    url  = "https://github.com/jmalonzo"
[[menu.main]]
    name = "LinkedIn"
    url  = "https://linkedin.com/in/jmalonzo"
