baseurl = "https://www.janalonzo.com"
languageCode = "en-us"
canonifyurls = true
title = "/public/"

[indexes]
    category = "categories"
    tag = "tags"

[Params]
    Author = "Jan Alonzo"
    Tagline = ""
    Description = "RANDOM INCONSEQUENTIAL MUSINGS"
