baseurl = "https://www.janalonzo.com"
#baseurl = "http://localhost:1313"
languageCode = "en-us"
canonifyurls = true
title = "/public/"

[indexes]
    category = "categories"
    tag = "tags"

[params]
    Tagline = ""
