baseurl = "https://www.janalonzo.com/"
languagecode = "en-US"
canonifyurls = true
title = "/public"
author = "Jan"
googleAnalytics = ""

[indexes]
    category = "categories"
    tag = "tags"

[params]
  name = "/public"
  description = ""
  copyright = "&copy; 2017 Jan Alonzo"

[params.offcanvas]
    # Menu items
    title = "Jan Alonzo"
    bio = "Sydney NSW"
    bio2 = "Australia"
    subscribe = "Subscribe"
    followme = "Contact"

    # Enable Google search
    search_enabled = true
    search = "Search"

    [[params.offcanvas.socialnetworks]]
        name = "jmalonzo [at] gmail"
        url = "mailto:jmalonzo@gmail.com"
