baseurl = "http://localhost:1313"
languagecode = "en-US"
canonifyurls = true
title = "/public"
author = "Jan"

[indexes]
    category = "categories"
    tag = "tags"

[params]
  name = "/public"
  description = ""
  copyright = "&copy; 2017 Jan Alonzo"
 
  pageNotFoundTitle = "Where could it be?"
  pageNotFoundSubtitle = "I wish that page exists, sorry. <br> Page not found."

[params.offcanvas]
    # Menu items
    title = "Jan Alonzo"
    bio = "Sydney NSW"
    bio2 = "Australia"
    subscribe = "Subscribe"
    followme = "Contact"

    # Enable Google search
    search_enabled = true
    search = "Search"

    [[params.offcanvas.socialnetworks]]
        name = "jmalonzo [at] gmail"
        url = "mailto:jmalonzo@gmail.com"
