baseurl = "https://www.janalonzo.com/"
languagecode = "en-US"
canonifyurls = true
title = "b-log"
googleAnalytics = "UA-594998-17"

pygmentsstyle = "emacs"
Paginate = 5
SectionPagesMenu = "main"


[indexes]
    category = "categories"
    tag = "tags"

[params]
  description = "My thoughts and musings"
  copyright = "&copy; 2018 Jan Alonzo"
  ShowCopyright = true
	RSSEnabled = true
  RSSSections = [ "Post" ]

[author]
  Handle = "jmalonzo"
  FirstName = "Jan"
  LastName = "Alonzo"
  AboutPage = "https://keybase.io/jmalonzo"
  Location = "Sydney, Australia"
  FlickrID = "52265670@N00"

[[menu.main]]
  name = "Post"
  weight = 1
  identifier = "post"
  url = "/post/"