baseurl = "https://www.janalonzo.com/"
languageCode = "en-us"
canonifyurls = true
title = "/public/"

googleAnalytics = "UA-594998-17"

[indexes]
    category = "categories"
    tag = "tags"

[Params]
    Author = "Jan Alonzo"
    Tagline = ""
    Description = "RANDOM INCONSEQUENTIAL MUSINGS"
    google_analytics = "UA-594998-17"
