# .circleci/config.yml
defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/project
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Building Vuepress site"
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths: dist/
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install awscli
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            export PATH=$HOME/.local/bin:$PATH
            pip install awscli --upgrade --user
            aws s3 sync dist s3://janalonzo.com/ --delete
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /index.html
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

