# .circleci/config.yml
defaults: &defaults
  docker:
    - image: felicianotech/docker-hugo:0.27.1
  working_directory: ~/project
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: yarn
      - run:
          name: "Build Our Statically Generated Docs Website with Hugo"
          command: HUGO_ENV=production npm run build
      - persist_to_workspace:
          root: /root/project
          paths: public/
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root/project
      - run:
          name: Sync to S3
          command: aws s3 sync public s3://janalonzo.com/ --delete
      - run: aws configure set preview.cloudfront true
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /index.html /index.xml
